name: Set Meraki password

on:
  pull_request:
  schedule:
      - cron: "0 12 * * *"

jobs:
  change-password:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: 3
        cache: 'pip'

    - name: Setup pips
      run: pip install -r meraki-80211x-users/requirements.txt

    - name: Run the script
      run: |
        cd meraki-80211x-users
        ./meraki-renew-user.py \
            --api-key ${{ secrets.MERAKI_API_KEY }} \
            --org 'Wailing Banshees' \
            --network 'ChezSquyres' \
            --ssid Yowza \
            --email meraki.guest@squyres.com
